"""In-process agent runtime: four-port loop, default pipelines, and synthetic defaults.

This module is the stable import path for the vocabulary a host needs to start a run and read
its events. Extension interfaces live in `agent_runtime.ports`, and the default components live
in their own subpackages.
"""

from agent_runtime.contracts import (
    CompletedEntry,
    CompletionCommand,
    ConsumedBudget,
    ExecutionLimits,
    ExternalWorkRef,
    Flow,
    FlowDecision,
    InvocationOutcome,
    Message,
    ModelEntry,
    ModelRequest,
    ModelResult,
    PendingRef,
    PreparedStep,
    RecordTarget,
    RecoveryBudget,
    Role,
    RunCancelled,
    RunControl,
    RunFailed,
    RunRequest,
    RunStarted,
    RunStatus,
    RunSucceeded,
    RuntimeEvent,
    RunWaiting,
    StepIdentity,
    StopReason,
    ToolBatchCommand,
    ToolBatchEntry,
    ToolCall,
    ToolChoice,
    ToolChoiceMode,
    ToolInvocation,
    ToolResult,
    ToolSpec,
)
from agent_runtime.exceptions import (
    AdapterError,
    AgentRuntimeError,
    BudgetExhaustedError,
    CancelledRunError,
    CapabilityError,
    CompletionProtocolError,
    ContextBudgetError,
    ProtocolError,
    RecordingError,
)
from agent_runtime.runner import DefaultRuntime, PortOverrides, assemble_default

__all__ = [
    "AdapterError",
    "AgentRuntimeError",
    "BudgetExhaustedError",
    "CancelledRunError",
    "CapabilityError",
    "CompletedEntry",
    "CompletionCommand",
    "CompletionProtocolError",
    "ConsumedBudget",
    "ContextBudgetError",
    "DefaultRuntime",
    "ExecutionLimits",
    "ExternalWorkRef",
    "Flow",
    "FlowDecision",
    "InvocationOutcome",
    "Message",
    "ModelEntry",
    "ModelRequest",
    "ModelResult",
    "PendingRef",
    "PortOverrides",
    "PreparedStep",
    "ProtocolError",
    "RecordTarget",
    "RecordingError",
    "RecoveryBudget",
    "Role",
    "RunCancelled",
    "RunControl",
    "RunFailed",
    "RunRequest",
    "RunStarted",
    "RunStatus",
    "RunSucceeded",
    "RunWaiting",
    "RuntimeEvent",
    "StepIdentity",
    "StopReason",
    "ToolBatchCommand",
    "ToolBatchEntry",
    "ToolCall",
    "ToolChoice",
    "ToolChoiceMode",
    "ToolInvocation",
    "ToolResult",
    "ToolSpec",
    "assemble_default",
]
